[2025-07-20T19:41:55.633+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-20T19:41:55.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_forecast.load_staging_to_mysql scheduled__2025-07-20T12:00:00+00:00 [queued]>
[2025-07-20T19:41:55.669+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_forecast.load_staging_to_mysql scheduled__2025-07-20T12:00:00+00:00 [queued]>
[2025-07-20T19:41:55.670+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-07-20T19:41:55.681+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_staging_to_mysql> on 2025-07-20 12:00:00+00:00
[2025-07-20T19:41:55.689+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_forecast', 'load_staging_to_mysql', 'scheduled__2025-07-20T12:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/fetch_weather_data.py', '--cfg-path', '/tmp/tmpfo0jqkus']
[2025-07-20T19:41:55.691+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask load_staging_to_mysql
[2025-07-20T19:41:55.691+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1590) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-20T19:41:55.692+0000] {standard_task_runner.py:63} INFO - Started process 1650 to run task
[2025-07-20T19:41:55.734+0000] {task_command.py:426} INFO - Running <TaskInstance: fetch_weather_forecast.load_staging_to_mysql scheduled__2025-07-20T12:00:00+00:00 [running]> on host 10a485cc97df
[2025-07-20T19:41:55.818+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_forecast' AIRFLOW_CTX_TASK_ID='load_staging_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-07-20T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-20T12:00:00+00:00'
[2025-07-20T19:41:55.820+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-20T19:41:55.821+0000] {logging_mixin.py:188} INFO - ƒêang load file: /opt/***/data/weather_20250720_194018.csv
[2025-07-20T19:41:55.824+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-20T19:41:55.824+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/load_to_staging_mysql.py", line 33, in load_staging_to_mysql
    df = pd.read_csv(latest_file)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1723, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 586, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
[2025-07-20T19:41:55.836+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=fetch_weather_forecast, task_id=load_staging_to_mysql, run_id=scheduled__2025-07-20T12:00:00+00:00, execution_date=20250720T120000, start_date=20250720T194155, end_date=20250720T194155
[2025-07-20T19:41:55.850+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task load_staging_to_mysql (No columns to parse from file; 1650)
[2025-07-20T19:41:55.866+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-20T19:41:55.881+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-20T19:41:55.883+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
